### ISSUE TITLE
concurrent map read and map write

### ISSUE THREAD

**Issue by gebv** [inpime/fader#11]
refactoring Map utils, thread-safe

```
fatal error: concurrent map read and map write

goroutine 8 [running]:
runtime.throw(0xd46160, 0x21)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:547 +0x90 fp=0xc820217ae8 sp=0xc820217ad0
runtime.mapaccess2_faststr(0xc44240, 0xc82040e8a0, 0xc8f738, 0x7, 0x30, 0xbf57c0)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/hashmap_fast.go:307 +0x5b fp=0xc820217b48 sp=0xc820217ae8
utils.M.Strings(0xc82040e8a0, 0xc8f738, 0x7, 0x0, 0x0, 0x0)
	/Users/gbv/work/src/_inpime/fader/src/utils/map.go:82 +0x9f fp=0xc820217cd0 sp=0xc820217b48
api/config.AppSettingsIncludeFiles(0x0, 0x0, 0x0)
	/Users/gbv/work/src/_inpime/fader/src/api/config/appconfig.go:37 +0x4e fp=0xc820217d08 sp=0xc820217cd0
api/config.ReloadAppSettings()
	/Users/gbv/work/src/_inpime/fader/src/api/config/appconfig.go:58 +0x67a fp=0xc820217f70 sp=0xc820217d08
api/utils.RefreshEvery(0x17d7840, 0xe07918)
	/Users/gbv/work/src/_inpime/fader/src/api/utils/refreshevery.go:12 +0x5c fp=0xc820217f90 sp=0xc820217f70
runtime.goexit()
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820217f98 sp=0xc820217f90
created by api/config.InitApp
	/Users/gbv/work/src/_inpime/fader/src/api/config/appconfig.go:80 +0x45
```

**Comment by gebv** [comment]
```
fatal error: concurrent map writes

goroutine 15 [running]:
runtime.throw(0xd11760, 0x15)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:547 +0x90 fp=0xc82006baa0 sp=0xc82006ba88
runtime.mapassign1(0xc44240, 0xc8202d6150, 0xc82006bc28, 0xc82006bc18)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/hashmap.go:445 +0xb1 fp=0xc82006bb48 sp=0xc82006baa0
utils.M.Strings(0xc8202d6150, 0xc8f738, 0x7, 0x0, 0x0, 0x0)
	/Users/gbv/work/src/_inpime/fader/src/utils/map.go:94 +0x52b fp=0xc82006bcd0 sp=0xc82006bb48
api/config.AppSettingsIncludeFiles(0x0, 0x0, 0x0)
	/Users/gbv/work/src/_inpime/fader/src/api/config/appconfig.go:37 +0x4e fp=0xc82006bd08 sp=0xc82006bcd0
api/config.ReloadAppSettings()
	/Users/gbv/work/src/_inpime/fader/src/api/config/appconfig.go:58 +0x67a fp=0xc82006bf70 sp=0xc82006bd08
api/utils.RefreshEvery(0x17d7840, 0xe07918)
	/Users/gbv/work/src/_inpime/fader/src/api/utils/refreshevery.go:12 +0x5c fp=0xc82006bf90 sp=0xc82006bf70
runtime.goexit()
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82006bf98 sp=0xc82006bf90
created by api/config.InitApp
	/Users/gbv/work/src/_inpime/fader/src/api/config/appconfig.go:80 +0x45

```

**Comment by gebv** [comment]
refactoring completed 
e943d7b3e166f4edce4774c9bc6dcab3ef4b1152
